SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `creation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(60) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `fichier` VARCHAR(255) NOT NULL,
  `galerie` VARCHAR(255) NULL DEFAULT NULL,
  `date_creation` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
